#!/bin/bash
#SBATCH --qos=debug
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=72
#SBATCH --cpus-per-task=2
#SBATCH -C cpu
#SBATCH -t 0:30:00
#SBATCH -J GaSb_plltest
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jackslurmjobs@gmail.com

export SLURM_CPU_BIND="cores"
export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=1
export HDF5_USE_FILE_LOCKING=FALSE

# QE parallelization parameters (problem-dependent)
nimage=1
npool=1
nband=1
ntg=1
ndiag=1

flags="-nimage $nimage -npool $npool -nband $nband -ntg $ntg -ndiag $ndiag"

#module load cpe/23.03
module load espresso/7.1-libxc-6.1.0-cpu
module load forge

cd 2.1-wfn
#perf-report 
srun -c 2 pw.x -input bands.in > bands.out -npool 8 -ndiag 1
srun -n 1 pw2bgw.x -input pw2bgw.in > pw2bgw.out
