#!/bin/bash
#SBATCH --qos=debug
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=map_gpu:0,1,2,3
#SBATCH --cpus-per-task=32
#SBATCH -C gpu
#SBATCH -t 0:30:00
#SBATCH -J GaSb
##SBATCH --mail-type=ALL
##SBATCH --mail-user=###
#SBATCH -A ####

export TEMPDIRPATH=$SCRATCH/tmp
export OMP_PROC_BIND=true
export OMP_PLACES=threads
export HDF5_USE_FILE_LOCKING=FALSE
export BGW_HDF5_WRITE_REDIST=1
export BGW_WFN_HDF5_INDEPENDENT=1
export OMP_NUM_THREADS=16
export SLURM_CPU_BIND="cores"
export MPIEXEC="`which srun` "

module load berkeleygw/4.0-gpu
#module swap PrgEnv-gnu PrgEnv-nvhpc ; module load cray-hdf5-parallel ; module load cray-fftw ; module load cray-libsci ; module load python

cd 1.1-epsilon-gpp-full
#srun epsilon.cplx.x > epsilon.out

cd 1.2-epsilon-gpp-pseudo
#srun epsilon.cplx.x > epsilon.out

cd ../1.3-epsilon-ff-pseudo
#srun -n 16 -c 32 epsilon.cplx.x > epsilon.out
